/*
@TargetNode='localhost'
@GeneratedBy=makean
@GenerationDate=08/16/2022 22:27:00
@GenerationHost=MARCGO3
*/

instance of MSFT_Credential as $MSFT_Credential1ref
{
Password = "Passw0rd2022";
 UserName = "MyTestAdminUser";

};

instance of MSFT_UserResource as $MSFT_UserResource1ref
{
UserName = "MyTestAdminUser";
 Password = $MSFT_Credential1ref;
 ModuleName = "PSDscResources";
 ModuleVersion = "2.12.0.0";
 Ensure = "Present";
 SourceInfo = "::12::9::User";
 ResourceID = "[User]AdminUser";
 ConfigurationName = "CreateAdminUser";
};
instance of MSFT_GroupResource as $MSFT_GroupResource1ref
{
GroupName = "Administrators";
 MembersToInclude = {
    "MyTestAdminUser"
};
 ModuleName = "PSDscResources";
 ModuleVersion = "2.12.0.0";
 Ensure = "Present";
 SourceInfo = "::2::1::Group";
 ResourceID = "[Group]Resource0::[GroupSet]AddUserToAdminGroup";
 ConfigurationName = "CreateAdminUser";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="makean";

                        GenerationDate="08/16/2022 22:27:00";

                        GenerationHost="MARCGO3";

                        Name="CreateAdminUser";

                    };
